# Generated by Django 3.1.6 on 2022-01-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='image',
        ),
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
